### ISSUE TITLE
project_name template variable not replaced in bin/heroku/setup

### ISSUE THREAD

**Issue by gibsonbailey** [ckc-org/skeletor#29]
<img width="864" alt="skeletor_project_name" src="https://user-images.githubusercontent.com/21694127/103307601-521dc600-49c5-11eb-8b91-aabe1369e390.png">
On the niceleads_backend project, this {{ project_name }} was not replaced, causing an error during heroku deployment.

**Comment by ckcollab** [comment]
Weird, did you use this exact command to boot the project up?

```
django-admin.py startproject new_project \
    --template=https://github.com/ckc-org/skeletor/archive/master.zip \
    --name bin/heroku/setup,app.json,README.md
```

Specifically mentions replacing name in `bin/heroku/setup` .. hmm..

**Comment by gibsonbailey** [comment]
Yeah it was successfully replaced in both app.json and README.md.

**Comment by gibsonbailey** [comment]
I'll try to reproduce it.

**Comment by ckcollab** [comment]
Damnit. I just reproduced, definitely busted .. weird.. I even tried with paths in quotes..
